"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
# populate variables with initial Fibonacci sequence numbers
fib_numbers = [1, 2]
fib_numbers_even = [2]

# generate list of Fibonacci sequence numbers up to 4,000,000
while fib_numbers[-1] <= 4000000:
    value = fib_numbers[-1] + fib_numbers[-2]
    fib_numbers.append(value)
    # check each addition to list - if even, add to new list containing even Fibonacci numbers
    if value % 2 == 0 and value < 4000000:
        fib_numbers_even.append(value)

# sum even fibonacci numbers
result = sum(fib_numbers_even)

print(result)
